services:
  - type: web
    name: fastapi-backend
    runtime: python
    buildCommand: ""
    startCommand: uvicorn app.main:app --host=0.0.0.0 --port=$PORT
    envVars:
      - key: ENV
        value: production
